import { Pool } from "@neondatabase/serverless";
import { Kysely, PostgresDialect } from "kysely";
import type { DB } from "./types"; // generated by kysely-codegen

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
pool.on("error", (err) => console.error("Idle client error", err));

export const db = new Kysely<DB>({ dialect: new PostgresDialect({ pool }) });
